FeedBack CRUD
pdp-adademy-g27/1fit-green-team pull request #14
Opened 2024-01-31 09:46 UTC by Qod1rc1k

FeedBack CRUD

2024-01-31 12:19 UTC, mavjudbekdev requested changes
Reponse dtoni togirlab qayta push qiling

2024-01-31 12:19 UTC, mavjudbekdev commented on src/main/java/com/example/onefit/feedback/dto/FeedBackResponseDto.java
> +public class FeedBackResponseDto {
respondto da malumot kam qaytgan

2024-02-01 03:55 UTC, Qod1rc1k commented on src/main/java/com/example/onefit/feedback/dto/FeedBackResponseDto.java
> +public class FeedBackResponseDto {
Buldi

2024-02-01 03:56 UTC, mavjudbekdev approved these changes

2024-02-01 03:57 UTC, merged