Role and Permission CRUD
pdp-adademy-g27/1fit-green-team pull request #2
Opened 2024-01-26 08:50 UTC by ezozafayzullayeva

2024-01-26 11:46 UTC, mavjudbekdev requested changes

2024-01-26 11:46 UTC, mavjudbekdev commented on src/main/java/com/example/onefit/user/permission/dto/PermissionResponseDto.java
> +    private UUID id;
NotBlank qolib ketgan

2024-01-26 11:46 UTC, mavjudbekdev commented on src/main/java/com/example/onefit/user/permission/dto/PermissionUpdateDto.java
> +public class PermissionUpdateDto {
bu yerda ham NotBlank qolib ketgan

2024-01-26 11:46 UTC, mavjudbekdev commented on src/main/java/com/example/onefit/user/role/dto/RoleResponseDto.java
> +public class RoleResponseDto {
NotBlank

2024-01-26 11:46 UTC, mavjudbekdev commented on src/main/java/com/example/onefit/user/role/dto/RoleUpdateDto.java
> +public class RoleUpdateDto {
NotBlank

2024-01-26 15:07 UTC, mavjudbekdev approved these changes

2024-01-26 15:24 UTC, ezozafayzullayeva commented
Role Permission CRUD to'g'irlandi

2024-01-27 06:27 UTC, ezozafayzullayeva commented
Role va Permission CRUD to'g'irlandi

2024-01-27 06:32 UTC, merged