Rating CRUD
pdp-adademy-g27/1fit-green-team pull request #3
Opened 2024-01-26 11:42 UTC by Qod1rc1k

rating CRUD

2024-01-26 11:57 UTC, mavjudbekdev requested changes

2024-01-26 11:57 UTC, mavjudbekdev commented on src/main/java/com/example/onefit/rating/RatingController.java
> +    public void delete(@PathVariable UUID id){
deleteda Response Notogri qaytarilgan

2024-01-26 11:57 UTC, mavjudbekdev commented on src/main/java/com/example/onefit/rating/RatingController.java
> +    }
update kerk emas

2024-01-26 11:57 UTC, mavjudbekdev commented on src/main/java/com/example/onefit/rating/dto/RatingUpdateDto.java
> +public class RatingUpdateDto {
bu ham kerk emas

2024-01-26 13:36 UTC, mavjudbekdev approved these changes

2024-01-27 08:51 UTC, merged

2024-01-27 08:52 UTC, Qod1rc1k commented
Rating CRUD